### ISSUE TITLE
getting repetitive value of date and time column in renko

### ISSUE THREAD

**Issue by joerusell9362** [ChillarAnand/stocktrends#14]
Hi @ChillarAnand,
I am trying to get renko data using following code:
```
from stocktrends import indicators
import pandas as pd

df = pd.read_csv('EUR-USD-RENKO-DATA.csv')

renko = indicators.Renko(df)

print('\n\nRenko box calcuation based on periodic close')
renko.brick_size = 0.0001
renko.chart_type = indicators.Renko.PERIOD_CLOSE
data = renko.get_ohlc_data()

data.to_csv('renko.csv')
```
And I am having follwing issues:
1) it tries to round off the value to brick size
2) date value is repetitive 

I don't know if my code is wrong. Can you please guide me if I have to make any changes to the code?
I have attach the zip file for data and my output and also a screenshot highlighting repetition.

Thanks

[files.zip](https://github.com/ChillarAnand/stocktrends/files/5898672/files.zip)

![Screenshot](https://user-images.githubusercontent.com/78277805/106372208-77db1980-633b-11eb-8607-a664036054f3.JPG)

**Comment by ChillarAnand** [comment]
@joerusell9362 Renko is based on brick calculation. So, it automatically round-off the values to brick size. This is expected.

Date values will be repetitive when there is more than 1 brick movement in price for that date. Since there is huge move in those duration, there are multiple entries.

**Comment by ChillarAnand** [comment]
Closing this issue for now. Feel free to re-open the issue if you need any help.
