### ISSUE TITLE
Legacy/Deprecated code warnings

### ISSUE THREAD

**Issue by Pilipets** [ChillarAnand/stocktrends#15]
FutureWarning: Slicing a positional slice with .loc is not supported, and will raise TypeError in a future version.  Use .loc with labels or .iloc with positions instead.
  self.cdf.loc[0, 1:] = [close - brick_size, close, close - brick_size, close]
  
 
This ticket is a reminder that the issue needs to be fixed in the upcoming releases.

```
from stocktrends import Renko
...
    renko = Renko(df)
    renko.brick_size = min(atr_brick_size, brick_size)
    renko_df = renko.get_ohlc_data()
...
```

**Comment by ChillarAnand** [comment]
Thanks for creating this issue, @Pilipets 

I will try to push a fix this week.

**Comment by ChillarAnand** [comment]
This issue is fixed in the latest release. Https://pypi.org/project/stocktrends/#history

**Comment by KemarReid** [comment]
I tried the new update and now the get_ohlc_data function produces a dataframe with only one row of data

**Comment by ChillarAnand** [comment]
There are multiple `get_ohlc_data` functions. For which indicator are you using? @KemarReid

**Comment by KemarReid** [comment]
I am having that issue with the get_ohlc_data belonging to the Renko Class. I haven't had any issues with the others

**Comment by ChillarAnand** [comment]
@KemarReid Created separate issue for this at https://github.com/ChillarAnand/stocktrends/issues/16.
