### ISSUE TITLE
price_movement_bricks is missing

### ISSUE THREAD

**Issue by kalusao** [ChillarAnand/stocktrends#4]
Hello Anand,

I get the following error. Indicators.py does not contain the function (def) price_movement_bricks :

AttributeError                            Traceback (most recent call last)
<ipython-input-86-5c2282d0a873> in <module>()
     14 # renko box calcuation based on price movement
     15 renko.chart_type = Renko.PRICE_MOVEMENT
---> 16 data = renko.get_ohlc_data()
     17 print(data.tail())

~/anaconda3/lib/python3.6/site-packages/stocktrends/indicators.py in get_ohlc_data(self)
     37             self.period_close_bricks()
     38         else:
---> 39             self.price_movement_bricks()
     40 
     41         return self.cdf

AttributeError: 'Renko' object has no attribute 'price_movement_bricks'

**Comment by ChillarAnand** [comment]
@kalusao Thanks for reporting the bug. I haven't pushed that part yet. I will push it and make a new relase.

**Comment by redallica** [comment]
Hey @ChillarAnand 
Just want to thank you for the great job you are doing here. I'm new to Python, and it seems very hard to find any code regarding Renko charts and Heikin Ashi charts. All the finance libraries are missing it. Even Matplotlib does not support Renko and Heikin Ashi charts. Do you know any way to get interactive Renko charts ? Maybe using bokeh or plotly ?

Looking forward to your new release
Best

**Comment by ChillarAnand** [comment]
@redallica I am not familiar with visualization tools and don't know if any package supports renko.

I will make a new release this weekend.

**Comment by redallica** [comment]
@kalusao 
Thanks. I will have a look into that. Did you use it by the way ?

**Comment by kalusao** [comment]
@redallica
Yes, I have played with that.

**Comment by redallica** [comment]
Hey @ChillarAnand 
Did you finally made your new release ?

**Comment by ChillarAnand** [comment]
@redallica Sorry for the delay. Got busy with some personal work. Will update in few days.

**Comment by karavind251** [comment]
Hi @ChillarAnand 
I am too waiting for price movement part.Could you please update on it

**Comment by HBK-HBK** [comment]
Hi @ChillarAnand

AttributeError: 'Renko' object has no attribute 'get_bricks'

Please let me know how to resolve it.

**Comment by otega99** [comment]
Hi @HBK-HBK  use .get_ohlc_data() instead

**Comment by ChillarAnand** [comment]
This is resolved sometime back. Please re-open if you face any issues.
