### ISSUE TITLE
Can we have the volume added to Renko 

### ISSUE THREAD

**Issue by tzvetkovg** [ChillarAnand/stocktrends#8]
When I call to get the renko bars as follows

renko_df = df2.get_ohlc_data()

how do I retrieve the volume as well? 

Thanks

**Comment by ChillarAnand** [comment]
@tzvetkovg Thanks for opening the issue. 

AFAIK, in Renko charts, both volume and time are eliminated. Renko is based only on price changes.

**Comment by ChillarAnand** [comment]
Closing this issue. Please re-open if you have any other questions.
