### ISSUE TITLE
Spyder always gave me the same error

### ISSUE THREAD

**Issue by alejivo** [ChillarAnand/stocktrends#9]
Hi i'm trying to build a class to wrap  renko charts but spyder always launch me the same error:

AttributeError: 'Renko' object has no attribute 'get_ohlc_data'
or 
AttributeError: 'Renko' object has no attribute 'get_bricks'

it's come from this method:

def __Convert2Renko(self):
        """
        Esta funcion de uso interno convierte el dataframe al renko
        """
        self.__DF_ohlc.reset_index(inplace=True)
        df_temp = pd.DataFrame()
        df_temp["date"] = self.__DF_ohlc[self.__DF_ohlc.columns[0]]
        df_temp["open"] = self.__DF_ohlc["Open"]
        df_temp["high"] = self.__DF_ohlc["High"]
        df_temp["low"] = self.__DF_ohlc["Low"]
        df_temp["close"] = self.__DF_ohlc["Close"]
        df_temp["volume"] = self.__DF_ohlc["Volume"]
        renko = Renko(df_temp)
        renko.brick_size = round(self.__ATRInterno(self.__DF_ohlc,self.__Periodo)["ATR"].tail(1),0)
        self.__DF_Renko = renko.get_ohlc_data() <-here alway launch the error

**Comment by alejivo** [comment]
I'm stalled from pip to git and fall in the same error again, then shouldn't be the version

**Comment by ChillarAnand** [comment]
@alejivo Thanks for submitting the issue. 

Can you check which version are you using?

```python
In [18]: import stocktrends                                                                                                                                                    

In [19]: stocktrends.__version__                                                                                                                                               
Out[19]: '0.1.0'

In [20]: hasattr(stocktrends.Renko, 'get_ohlc_data')                                                                                                                           
Out[20]: True
```

**Comment by ChillarAnand** [comment]
Closing this issue as there is no further response. Feel free to re-open the issue if you can add more information regarding the same. @alejivo

**Comment by amritmohanty89** [comment]
how to upgrade the stocktrends version from 0.1.0 to 0.1.5

**Comment by ChillarAnand** [comment]
```
$ python3 -m pip install --upgrade stocktrends      
```

@amritmohanty89
